# Generated by Django 2.1.7 on 2019-03-26 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='last_updatad_time',
            new_name='last_updated_time',
        ),
    ]
